model:
  agent_type: PPO
  batch_size: 2048
  device: auto
  eval_freq: 10000
  gamma: 0.99
  learning_rate: 0.0003
  log_freq: 1000
  net_dims:
  - 128
  - 64
  save_freq: 50000
  seed: 42
  total_timesteps: 1000000
trading:
  data_source: yahoo
  initial_capital: 1000000.0
  max_leverage: 1.5
  max_position_size: 0.2
  max_stock_quantity: 100
  min_cash_reserve: 0.1
  rebalance_frequency: daily
  slippage_pct: 0.0005
  stop_loss_pct: 0.05
  take_profit_pct: 0.15
  trading_hours:
  - 09:30
  - '16:00'
  transaction_cost_pct: 0.001
  update_frequency: 1min
